### ISSUE TITLE
Is radio really a dependency?

### ISSUE THREAD

**Issue by jaustin** [Seeed-Studio/pxt-grove-zero-for-microbit#1]
Trying to import this package with Bluetooth already used, I had to remove Bluetooth.

One common use-case for sensor boards is to log data over BLE. Is there any reason for the radio dependency on this module?

I think it's the following line that causes 'Bluetooth' to be removed
https://github.com/Seeed-Studio/pxt-grove-zero-for-microbit/blob/master/pxt.json#L8

My guess is that this is leftover from earlier development?

**Comment by WayenWeng** [comment]
Remove the radio dependency, you can test again.

**Comment by jaustin** [comment]
Hi @WayenWeng I can test the adding in the IDE, but we need to rely on package authors like you to ensure that all the features of the package work properly with all the listed dependencies. Please can you test there? I can confirm that the package can now be added, but that doesn't guarantee that it will work!

**Comment by WayenWeng** [comment]
Hi @jaustin It is our duty to keep the package working. Now there is a beta version, but we will do our best to solve any issues. You can rest assured to use the package. Thanks for your reminding.
