### ISSUE TITLE
Update and pxt-bump for makecode v1

### ISSUE THREAD

**Issue by microbit-mark** [Seeed-Studio/pxt-grove-zero-for-microbit#2]
Please can you run a release for the updated makecode editor.

**Comment by MiroChao** [comment]
@microbit-mark Hi Mark, we've updated the package for supporting makecode v1, do we need to get a new approval ?

**Comment by MiroChao** [comment]
@microbit-mark The extension blocks are not updated as the main.ts file

**Comment by microbit-mark** [comment]
you'll just need to create a new release https://github.com/Seeed-Studio/pxt-grove-zero-for-microbit/releases

**Comment by MiroChao** [comment]
OK, thank you, it works.

**Comment by MiroChao** [comment]
@microbit-mark Hi Mark, I've updated the **icon.png** image as well, somehow it's not updated, any chance you know why?

**Comment by MiroChao** [comment]
@microbit-mark  Hi Mark, how can I get my new extensions authorized and searchable in makecode?

**Comment by microbit-mark** [comment]
See https://support.microbit.org/a/solutions/articles/19000054952
